[package]
name = "gptermial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
openssl = "0.10.62"
serde_json = "1.0.111"

[[bin]]
name = "gptermial"
path = "main.rs"
